apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    basicAuth: false
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
    editable: true

  - name: Metrics Service API
    type: grafana-simple-json-datasource
    access: proxy
    url: http://metrics-service:3000/api
    isDefault: false
    basicAuth: false
    jsonData:
      keepCookies: []
    editable: true
